# Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. 

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:


In [1]:
import numpy as np

a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a))            # Prints "<type 'numpy.ndarray'>"
print(a.shape)           # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                 # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b.shape)                    # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


Numpy also provides functions to instantiate and populate arrays. See some of them here, but don't forget to take a look at the docs!

In [11]:
a = np.zeros((2,2))    # Creates a 2D matrix of 0s
print(a)

b = np.ones((5))       # Creates a list of 1s with size 5
print(b)

c = np.full((3,3),5)   # Creates a 3x3 matrix of 5s
print(c)

d = np.eye(2)          # Creates a 2x2 identity matrix
print(d)

e = np.random.random((2,2))   # Creates a 2x2 array with random values
print(e)

[[ 0.  0.]
 [ 0.  0.]]
[ 1.  1.  1.  1.  1.]
[[ 5.  5.  5.]
 [ 5.  5.  5.]
 [ 5.  5.  5.]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.60173311  0.6478764 ]
 [ 0.94969534  0.00465772]]


/usr/local/lib/python3.5/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((3, 3), 5) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


### Array Slicing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [13]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


In [15]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [20]:
b = a[2:3, 0:3]
b

array([[ 9, 10, 11]])